apiVersion: apps/v1
kind: Deployment
metadata:
  name: conatiner-app-deployment
  labels:
    app: container-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: container-app
  template:
    metadata:
      labels:
        app: container-app
    spec:
      containers:
      - name: conatiner-app
        image: aqibmukhtar/app-container-security:latest
        ports:
        - containerPort: 8080

